source 'http://rubygems.org'

gem 'rails', '3.2.22'

group :assets do
  gem 'coffee-rails', '~> 3.2.2'
  gem 'coffee-script-source', '~> 1.6.3'
  gem 'uglifier', '~> 2.7.2'

  gem 'uploadcare-widget', path: '../..'
end

group :development, :test do
  gem 'jasminerice', :git => 'https://github.com/bradphelan/jasminerice.git'
  gem 'rb-fsevent', '~> 0.9'
  gem 'guard', '~> 1.8'
  gem 'guard-jasmine'
  gem 'rails-dev-tweaks', '~> 1.2.0'
  gem 'therubyracer'
  gem 'ejs', :git => 'git@github.com:uploadcare/ruby-ejs.git'
end
