source 'https://rubygems.org'

gem 'rails', '3.2.8'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'yui-compressor'
  gem 'uploadcare-widget', path: '../..'
end

gem 'jquery-rails'
